* Методические пояснения к циклу семинарско-лабораторных занятий по курсу "ЭЛЕКТРОННЫЕ МЕТОДЫ ФИЗИЧЕСКИХ ИССЛЕДОВАНИЙ" на 4-м курсе ФОПФ
** # 24 Безынерционные цепи
*** Занятие 1
Семинар. Теорема об эквивалентном генераторе, делитель напряжения, параллельный сумматор. Знакомство с матричным описанием трехполюсников. Техника измерения (вычисления) Н-параметров.

Практика. На макетной плате исследуем делитель и параллельный сумматор. Знакомимся с Micro-Cap. Измеряем H-параметры.

Домашнее задание: Выразить X-параметры через H-параметры.

*** Занятие 2
Семинар. X,Y параметры, преобразование треугольник-звезда. Передаточная матрица, характеристическое сопротивление. Матрицы волновых параметров.

Практика. Завершаем исследования в Micro-Cap.

Домашнее задание: Прочесть методичку к работе 18.

Сдача работы, итоговая оценка.

** # 18  Пассивные электрические цепи»
*** Занятие 1
Семинар. Представление об импульсной реакции и передаточной функции. Интегрирующая и дифференцирующая цепи. Комплексная мощность. 

Практика. Выполняем задание 1. 

Домашнее задание: Вывести формулу для передаточной функции одной из RC-цепей второго порядка.

*** Занятие 2
Семинар. Фазовращатели, двойной Т-мост, фильтры с последовательным колебательным контуром.

Практика. Выполняем задание 3 и 4 в Micro-Cap (без сборки фильтров на плате). 

Домашнее задание: С помощью преобразования Лапласа вычислить переходные характеристики трех типов фильтров второго порядка.  Читаем по методичке преамбулы к заданиям 5 и 6.

*** Занятие 3
Семинар. Обсуждение вопросов по параллельному и смешанному резонансам.

Практика. Выполняем задание 5 и 6. 

Домашнее задание: Прочесть методичку к работе по длинным линиям.

Сдача работы, итоговая оценка.

** # 91	Длинная линия
*** Занятие 1
Семинар. Обсуждение экспериментов по измерению параметров длиной линии.

Практика. Измеряем параметры линии. 

Домашнее задание: Представить график распределения напряжения вдоль линии (стояча волна) в режиме холостого хода, короткого замыкания.

*** Занятие 2
Семинар. Обсуждаем переходные процессы в длинной линии.

Практика. Наблюдаем переходные процессы в Micro-Cap. 

Домашнее задание: Прочитать первую главу Краткого экскурса в электронику А. Григорьева (текст доступен в pdf)

Сдача работы, итоговая оценка. Во внимание принимаются результаты измерения параметров линии и умение объяснить переходный процесс в линии при заданной комбинации коэффициентов отражения.

** # 28	Усилитель на биполярном транзисторе
*** Занятие 1
Семинар. Обсуждаем нестабилизированную схему – начальный режим, коэффициент усиления, входное сопротивление, граничные частоты.

Практика. Собираем схему и проводим измерения. 

Домашнее задание: Предсказать изменение параметров при замене Rb на 2 Rb и при введении нагрузки.

*** Занятие 2
Семинар. Обсуждаем поведение параметров при замене Rb на 2 Rb и при введении нагрузки. Учимся задавать начальный режим стабилизированной схемы.

Практика. Проводим измерения для схем с 2Rb и нагрузкой. 

Домашнее задание: Рассчитать элементы стабилизированной схемы.

*** Занятие 3
Семинар. Обсуждаем схемы с общим коллектором и базой.

Практика. Проводим измерения для стабилизированных схем. Заполняем таблицу. 

Домашнее задание: Прочитать раздел «Дифференциальная схемотехника» по Григорьеву с. 67-80.

Сдача работы, итоговая оценка.

** # 90 Дифференциальный усилитель
*** Занятие 1
Семинар. Отвечаем на вопросы по теории.

Практика. Собираем схему с резистором в качестве генератора тока. Измеряем ее коэффициенты усиления и входные сопротивления. 

Домашнее задание: Оценить эквивалентное сопротивление генератора стабильного тока на транзисторе.

*** Занятие 2
Семинар. Обсуждаем схему с токовыми зеркалами в качестве источника тока и динамической нагрузки.

Практика. Исследуем ее характеристики в Micro-Cap. 

Домашнее задание. Прочитать введение в теорию обратных связей (с. 81-88) и раздел «Операционные усилители» со с. 101 по Григорьеву

Сдача работы, итоговая оценка.

** # 77 Операционный усилитель
*** Занятие 1
Семинар. Отвечаем схемы масштабных усилителей, принцип виртуального замыкания.

Практика. Измеряем коэффициент усиления ОУ и исследуем схемы инвертирующего и неинвертирующего усилителей.

Домашнее задание: Разобраться в схемах сумматора, вычитателя и дифференциального усилителя на ОУ.

*** Занятие 2
Семинар. Обсуждаем схемы с двойной обратной связью – конвертор и инвертор сопротивления, источник тока.

Практика. Исследуем схему с отрицательным сопротивлением на макете и схему имитатора индуктивности в Micro-Cap.

Домашнее задание: Разобраться со схемой источника тока и гиратора.

*** Занятие 3
Семинар. Обсуждаем триггер Шмидта и мультивибратор.

Практика. Исследуем схему мультивибратора.

Домашнее задание: Продолжить обучение на физтехе.

Сдача работы, итоговая оценка.


Cоставил доцент  А.А.ГРИГОРЬЕВ.
